# This is a basic workflow that is manually triggered

name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com/mpsec/mpsec/mpsec-app
          username: wnsgml972
          password: ${{ secrets.PACKAGES_READ_WRITE }}
      - 
          name: nana2
          run: echo ${{ secrets.PACKAGES_READ_WRITE }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: user/app:latest
          cache-from: type=registry,ref=user/app:latest
          cache-to: type=inline
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.PACKAGES_READ_WRITE }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
